"""Run summaries (runs/YYYY-MM.md) and the regenerated README."""
from __future__ import annotations

from datetime import datetime

import pandas as pd

from rtb import maps
from rtb.aggregate import Headline
from rtb.api import ComboHarvest
from rtb.checks import CheckResult


def _pct(h: Headline) -> str:
    return f"{h.rate:.1f}%"


def run_summary(run_id: str, run_at: datetime, harvests: list[ComboHarvest], result: CheckResult,
                total: int, prev_total: int | None, database_total: int | None,
                store_total: int | None, heads: list[Headline] | None, requests: int) -> str:
    status = {"ok": "OK", "warn": "WARNINGS", "fail": "FAILED"}[result.status]
    delta = f"{total - prev_total:+,d}" if prev_total is not None else "n/a (first run)"
    lines = [
        f"# Harvest {run_id}: {status}",
        "",
        f"- Run at: {run_at:%Y-%m-%d %H:%M} UTC",
        f"- Decisions harvested: {total:,}",
        f"- Previous run: {prev_total:,}" if prev_total is not None else "- Previous run: none",
        f"- Delta: {delta}",
        f"- API `total_database_records`: {database_total:,}" if database_total is not None else "",
        f"- Decisions in store: {store_total:,}" if store_total is not None else "- Store: not updated (run failed)",
        f"- API requests: {requests}",
        "",
    ]
    if result.errors:
        lines += ["## Errors (run failed, nothing committed)", ""] + [f"- {e}" for e in result.errors] + [""]

    lines += ["## Unknown enum values", ""]
    if result.unknown_enums:
        lines += [
            "**New values the maps do not know about. Add them to `rtb/maps.py` before the next publication.**",
            "",
            "| field | value | occurrences |",
            "|---|---:|---:|",
        ]
        for fld, values in sorted(result.unknown_enums.items()):
            lines += [f"| `{fld}` | {v} | {n:,} |" for v, n in sorted(values.items())]
    else:
        lines.append("None.")
    lines.append("")

    other_warnings = [w for w in result.warnings if not w.startswith("UNKNOWN ")]
    lines += ["## Warnings", ""] + ([f"- {w}" for w in other_warnings] or ["None."]) + [""]
    if result.notes:
        lines += ["## Notes", ""] + [f"- {n}" for n in result.notes] + [""]

    lines += ["## Census", "", "| combination | census | harvested | match |", "|---|---:|---:|:---:|"]
    for h in sorted(harvests, key=lambda h: h.combo.key):
        ok = "yes" if len(h.decisions) == h.census else "**NO**"
        lines.append(f"| {h.combo.key} | {h.census:,} | {len(h.decisions):,} | {ok} |")
    lines.append("")

    if heads:
        lines += ["## Headline figures (RTA only)", "", "| measure | success | granted | dismissed |",
                  "|---|---:|---:|---:|"]
        lines += [f"| {h.label} | {_pct(h)} | {h.granted:,} | {h.dismissed:,} |" for h in heads]
        lines.append("")

    return "\n".join(line for line in lines if line is not None) + "\n"


def readme(run_at: datetime, total: int, rta_total: int, heads: list[Headline],
           first_decision: pd.Timestamp, last_decision: pd.Timestamp) -> str:
    rows = "\n".join(
        f"| {h.label} | **{_pct(h)}** | {h.granted:,} | {h.dismissed:,} |" for h in heads
    )
    return f"""# BC Residential Tenancy Branch decision outcomes

Structured outcome data for every decision the BC Residential Tenancy Branch (RTB) has posted
to its public decision search, re-harvested in full each month.

> **This is independent analysis. It is not official RTB statistics** and is not endorsed by
> the Residential Tenancy Branch or the Province of British Columbia.

<!-- Everything between these markers is regenerated by the pipeline. Do not edit by hand. -->
<!-- BEGIN GENERATED -->
_Last harvested {run_at:%d %B %Y}. {total:,} decisions in total, of which {rta_total:,} were decided
under the Residential Tenancy Act. Decision dates {first_decision:%d %b %Y} to {last_decision:%d %b %Y}._

## Headline figures

Residential Tenancy Act disputes only.

| measure | success rate | claims granted | claims dismissed |
|---|---:|---:|---:|
{rows}
<!-- END GENERATED -->

## Methodology

**Unit of analysis.** Each decision lists one or more claims (for example, an order of possession,
a monetary order, or cancellation of a notice to end tenancy), each with its own outcome. Figures
are counted per claim, not per decision.

**Success rate** is `granted / (granted + dismissed)`. Claims that were settled, withdrawn, or
otherwise not decided on their merits are outside the denominator.

**Residential Tenancy Act only by default.** The RTB also decides manufactured home park site
disputes, under a different statute: the *Manufactured Home Park Tenancy Act*. Those decisions
are kept in the row-level data (`rental_type == "ManufHome"`) and in the aggregate CSV, but they
are excluded from every headline figure above. Filter to `rental_type == "Home"` to reproduce them.

**Coverage.** The posted decision search starts on 21 December 2022 for direct request decisions
and 16 June 2023 for participatory hearing decisions. Earlier decisions are not in the source.
Posting lags decision writing by a variable amount, so the most recent months grow after the fact.

**Collection.** Each run re-harvests the entire corpus and upserts by the RTB's anonymised decision
ID. Every run must reconcile the number of decisions collected for each of the 16 facet
combinations against the count the API reports, or it fails and publishes nothing. Git history
on this repository is the time series: each monthly commit is a dated snapshot.

## Files

| file | contents |
|---|---|
| `data/rtb_outcomes_by_claim.csv` | Published aggregate: claims by applicant, process, rental type, tenancy status and claim code, with granted / dismissed / settled / other counts |
| `data/decisions.parquet` | One row per decision: facets, dates, flags |
| `data/outcomes.parquet` | One row per claim: decision ID, claim code, remedy status fields |
| `rtb/claim_codes.json` | Claim code acronyms and titles, from the RTB site's own issue configuration |
| `data/census.json` | Per run, per facet combination: expected vs harvested |
| `runs/YYYY-MM.md` | Run summaries: totals, growth, unknown codes, warnings |

## Licence

The structured data here (facets, dates, claim codes and outcomes) is published as factual
metadata. **The decisions themselves are not included and are not redistributed.** The
arbitrators' written reasons are Crown copyright; read them at the
[RTB decision search](https://tenancydispute.gov.bc.ca/).
"""
